In [1]:
import numpy as np
from numpy import linalg

***Задание 1*** <br />
Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

In [2]:
n = 10
x = np.flip(np.arange(0,n))
x

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

***Задание 2*** <br />
Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [3]:
n = 10
xmatrix = np.diag(np.flip(np.arange(0,n)), k=0)
xmatrix

array([[9, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 8, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 7, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 6, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 5, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 4, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 3, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 2, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [4]:
xmatrix.trace()

45

***Задание 3*** <br />
Решите систему уравнений: <br />
4x + 2y + z = 4 <br />
x + 3y = 12 <br />
5y + 4z = -3 <br />

In [5]:
a = np.array( [ [4, 2, 1], [1, 3, 0], [0, 5, 4] ] )

In [6]:
b = np.array( [4, 12, -3] )

In [7]:
linalg.solve(a, b)

array([ 0.46666667,  3.84444444, -5.55555556])

In [8]:
np.allclose( np.dot(a, linalg.solve(a, b)), b )

True

***Задание 4*** <br />
В материалах занятия раздел “Задача 4 домашнего задания”

Имеется матрица покупок в интернет-магазине. Столбец А - ID пользователя. Остальные столбцы - количество покупок категорий товаров этим пользователем:

In [9]:
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)

In [10]:
next_user_stats = np.array([0, 1, 2, 0, 0, 0])

Найдите самого похожего пользователя. Т. е. посчитайте косинусное расстояние между этим пользователем и всеми пользователями из массива user_stats

In [11]:
users_comparsion = {}
a = next_user_stats
i = -1

for existing_user in users_stats:
    i += 1
    b = existing_user
    aLength = np.sqrt( (a*a).sum() )
    bLength = np.sqrt( (b*b).sum() )
    cos = np.dot( a, b ) / ( aLength * bLength )
    users_comparsion.setdefault(i,cos)
closest_user_id = max(users_comparsion, key=users_comparsion.get)
closest_user_id

7